//! 工具函数 —— 对应 Java `freemarker.template.utility.*`
//! （一文件一 Java 对象；fnv.rs 为 Rust 特有）

mod capture_output;
mod class_util;
mod collection_utils;
mod collections12;
mod constants;
mod date_util;
mod deep_unwrap;
mod dom_node_model;
mod execute;
mod fnv;
mod html_escape;
mod normalize_newlines;
mod null_argument_exception;
mod null_writer;
mod number_util;
mod object_constructor;
mod object_factory;
mod object_wrapper_with_api_support;
mod optimizer_util;
mod rich_object_wrapper;
mod security_utilities;
mod standard_compress;
mod string_util;
mod template_model_utils;
mod to_canonical;
mod undeclared_throwable_exception;
mod unrecognized_time_zone_exception;
mod unsupported_number_class_exception;
mod write_protectable;
mod xml_escape;

pub use capture_output::CaptureOutputTransform;
pub use class_util::ClassUtil;
pub use collection_utils::CollectionUtils;
pub use collections12::Collections12;
pub use constants::Constants;
pub use date_util::DateUtil;
pub use deep_unwrap::DeepUnwrap;
pub use dom_node_model::DOMNodeModel;
pub use execute::Execute;
pub use fnv::{FnvBuildHasher, FnvHasher};
pub use html_escape::{html_escape_entity, HtmlEscapeTransform};
pub use normalize_newlines::{normalize_newlines_text, NormalizeNewlinesTransform};
pub use null_argument_exception::{check as check_not_null, NullArgumentException};
pub use null_writer::NullWriter;
pub use number_util::NumberUtil;
pub use object_constructor::ObjectConstructorFn;
pub use object_factory::ObjectFactory;
pub use object_wrapper_with_api_support::ObjectWrapperWithAPISupport;
pub use optimizer_util::OptimizerUtil;
pub use rich_object_wrapper::RichObjectWrapper;
pub use security_utilities::SecurityUtilities;
pub use standard_compress::{standard_compress_text, StandardCompressTransform};
pub use string_util::{glob_to_regex, html_enc_legacy, html_escape, java_trim, xml_escape};
pub use template_model_utils::TemplateModelUtils;
pub use to_canonical::ToCanonical;
pub use undeclared_throwable_exception::UndeclaredThrowableException;
pub use unrecognized_time_zone_exception::UnrecognizedTimeZoneException;
pub use unsupported_number_class_exception::UnsupportedNumberClassException;
pub use write_protectable::WriteProtectable;
pub use xml_escape::XmlEscapeTransform;
