//! 对应 Java `freemarker.core` 包：解析器产物、渲染引擎、算术引擎、设置项

pub(crate) mod _array_enumeration;
mod _array_iterator;
mod _core_api;
mod _core_locale_utils;
mod _core_string_utils;
mod _delayed_a_or_an;
mod _delayed_conversion_to_string;
mod _delayed_ftl_type_description;
mod _delayed_get_canonical_form;
mod _delayed_get_message;
mod _delayed_get_message_without_stack_top;
mod _delayed_j_quote;
mod _delayed_join_with_comma;
mod _delayed_ordinal;
mod _delayed_short_class_name;
mod _delayed_to_string;
mod _error_description_builder;
mod _java16;
mod _java16_impl;
mod _java9;
mod _java9_impl;
mod _markup_builder;
mod _message_util;
pub(crate) mod _misc_template_exception;
mod _object_builder_setting_evaluation_exception;
mod _object_builder_setting_evaluator;
mod _parser_configuration_with_inherited_format;
mod _setting_evaluation_environment;
mod _sorted_array_set;
mod _template_model_exception;
mod _time_zone_builder;
mod _unexpected_type_error_explainer_template_model;
mod _unmodifiable_composite_set;
mod _unmodifiable_set;
mod abstract_json_like_format;
mod alias_target_template_value_format_exception;
mod alias_template_date_format_factory;
mod alias_template_number_format_factory;
mod api_not_supported_template_exception;
mod apinot_supported_template_exception;
mod arithmetic_engine;
mod assignment;
mod assignment_instruction;
mod attempt_block;
mod auto_esc_block;
mod backward_compatible_template_number_format;
mod block_assignment;
mod body_instruction;
mod boolean_expression;
mod break_instruction;
mod break_or_continue_exception;
mod bug_exception;
mod built_in_banned_when_auto_escaping;
mod built_in_banned_when_forced_auto_escaping;
mod built_in_for_date;
mod built_in_for_hash_ex;
mod built_in_for_legacy_escaping;
mod built_in_for_loop_variable;
mod built_in_for_markup_output;
mod built_in_for_node;
mod built_in_for_node_ex;
mod built_in_for_number;
mod built_in_for_sequence;
mod built_in_for_string;
mod built_in_with_direct_call_optimization;
mod built_in_with_parse_time_parameters;
pub(crate) mod built_ins_for_callables;
pub(crate) mod built_ins_for_dates;
pub(crate) mod built_ins_for_existence_handling;
pub(crate) mod built_ins_for_hashes;
pub(crate) mod built_ins_for_loop_variables;
pub(crate) mod built_ins_for_markup_outputs;
pub(crate) mod built_ins_for_multiple_types;
pub(crate) mod built_ins_for_nodes;
pub(crate) mod built_ins_for_numbers;
mod built_ins_for_output_format_related;
pub(crate) mod built_ins_for_sequences;
pub(crate) mod built_ins_for_strings_basic;
pub mod built_ins_for_strings_encoding;
pub(crate) mod built_ins_for_strings_misc;
pub(crate) mod built_ins_for_strings_regexp;
pub(crate) mod built_ins_with_lazy_conditionals;
mod c_format;
mod c_template_number_format;
mod call_place_custom_data_initialization_exception;
mod r#case;
mod collection_and_sequence;
mod combined_markup_output_format;
mod command_line;
mod comment;
mod common_markup_output_format;
mod common_template_markup_output_model;
mod compressed_block;
mod conditional_block;
mod configurable;
mod continue_instruction;
mod css_output_format;
mod custom_attribute;
mod debug_break;
mod default_truncate_builtin_algorithm;
mod directive_call_place;
mod dollar_variable;
mod dot_before_method_call;
mod dynamic_key_name_before_method_call;
mod else_of_list;
pub(crate) mod environment;
mod escape_block;
pub(crate) mod eval;
pub(crate) mod eval_util;
mod exec;
mod expression;
mod expression_with_fixed_result;
mod extended_decimal_format_parser;
mod fallback_instruction;
mod flow_control_exception;
mod flush_instruction;
mod free_marker_tree;
mod ftl_header;
mod get_optional_template_method;
mod global_assignment;
mod hash_literal;
mod html_output_format;
mod ici_chain_member;
mod if_block;
mod include;
mod intermediate_stream_operation_like_builtin;
mod interpolation;
mod interpret;
mod invalid_format_parameters_exception;
mod invalid_format_string_exception;
pub(crate) mod invalid_reference_exception;
mod iso_like_template_date_format;
mod iso_like_template_date_format_factory;
mod iso_template_date_format;
mod iso_template_date_format_factory;
mod items;
mod iterator_block;
mod java_c_format;
mod java_script_c_format;
mod java_script_or_jsonc_format;
mod java_script_output_format;
mod java_template_date_format;
mod java_template_date_format_factory;
mod java_template_number_format;
mod java_template_number_format_factory;
mod json_output_format;
mod json_parser;
mod jsonc_format;
mod lazily_generated_collection_model;
mod lazily_generated_collection_model_ex;
mod lazily_generated_collection_model_with_already_known_size;
mod lazily_generated_collection_model_with_same_size_coll_ex;
mod lazily_generated_collection_model_with_same_size_seq;
mod lazily_generated_collection_model_with_unknown_size;
mod lazy_collection_template_model_iterator;
mod lazy_sequence_iterator;
mod legacy_c_format;
mod legacy_constructor_parser_configuration;
mod library_load;
mod list_else_container;
mod local_assignment;
mod local_context;
mod local_context_stack;
#[path = "macro.rs"]
mod r#macro;
mod macro_def;
mod markup_output_format;
mod markup_output_format_bound_builtin;
pub(crate) mod misc_template_exception;
mod misc_util;
mod mixed_content;
mod nested_content_not_supported_exception;
mod new_bi;
mod no_auto_esc_block;
mod no_escape_block;
mod non_boolean_exception;
mod non_date_exception;
mod non_extended_hash_exception;
mod non_extended_node_exception;
mod non_hash_exception;
mod non_listable_right_unbounded_range_model_exception;
mod non_markup_output_exception;
mod non_method_exception;
mod non_namespace_exception;
mod non_node_exception;
mod non_numerical_exception;
mod non_sequence_exception;
mod non_sequence_or_collection_exception;
mod non_string_exception;
mod non_string_or_template_output_exception;
mod non_user_defined_directive_like_exception;
mod numerical_output;
mod on;
mod opt_in_template_class_resolver;
mod output_format;
mod output_format_block;
mod output_format_bound_builtin;
mod parameter_role;
mod parse_exception;
mod parser_configuration;
mod parsing_not_supported_exception;
mod plain_text_output_format;
mod property_setting;
mod range_model;
mod recovery_block;
mod recurse_node;
mod regexp_helper;
mod return_exception;
mod return_instruction;
mod right_unbounded_range_model;
mod rtf_output_format;
mod sep;
mod sequence_iterator;
mod single_iteration_collection_model;
mod special_built_in;
mod standard_c_formats;
mod stop_exception;
mod stop_instruction;
mod string_array_sequence;
mod switch_block;
mod template_class_resolver;
pub(crate) mod template_combined_markup_output_model;
mod template_configuration;
mod template_date_format;
mod template_date_format_factory;
mod template_element;
mod template_element_array_builder;
mod template_elements_to_visit;
pub(crate) mod template_exception;
mod template_format_util;
mod template_html_output_model;
mod template_markup_output_model;
mod template_model_exception;
mod template_not_found_exception;
mod template_null_model;
mod template_number_format;
mod template_number_format_factory;
mod template_object;
mod template_output_model;
mod template_plain_output_model;
pub(crate) mod template_post_processor;
pub(crate) mod template_post_processor_exception;
mod template_processing_tracer;
mod template_rtf_output_model;
mod template_value_format;
mod template_value_format_exception;
mod template_value_format_factory;
mod template_xhtml_output_model;
mod template_xml_output_model;
mod text_block;
pub(crate) mod thread_interruption_support_template_post_processor;
mod transform_block;
mod trim_instruction;
mod truncate_builtin_algorithm;
mod undefined_custom_format_exception;
mod undefined_output_format;
pub(crate) mod unexpected_type_exception;
mod unformattable_value_exception;
mod unified_call;
mod unknown_date_type_formatting_unsupported_exception;
mod unknown_date_type_parsing_unsupported_exception;
mod unparsable_value_exception;
mod unregistered_output_format_exception;
mod visit_node;
mod xhtml_output_format;
mod xml_output_format;
mod xs_template_date_format;
mod xs_template_date_format_factory;
mod xsc_format;

pub use arithmetic_engine::{ArithmeticEngine, BigDecimalEngine};
pub use combined_markup_output_format::{CombinedMarkupOutputFormat, CombinedMarkupOutputModel};
pub use configurable::{canonical_setting_key, java_time_zone_id, Settings, TzSetting};
pub use environment::{render, Environment, MacroValue, Namespace};
pub use eval::{compare_models, eval, CmpOp};
pub use eval_util::{
    arg_count, arg_number, arg_string, check_arg_count, coerce_to_string, models_equal,
    target_string,
};
pub use exec::{exec, ExecOutcome};
pub use expression::{
    AddConcatExpression, AndExpression, BuiltinVar, Expr, ExprKind, OrExpression, RangeKind,
    StrPart,
};
pub use macro_def::{MacroDef, MacroParam};
pub use output_format::{
    escape_markup, mime_type, parse_combined_markup_format, AutoEscaping, OutputFormatKind,
};
pub use range_model::RangeSpec;
pub use template_class_resolver::{NewBuiltinClassResolver, OptInClassResolver};
pub use template_configuration::TemplateConfiguration;
pub use template_element::{AssignOp, CallTarget, CaseDef, Element, ElementKind};
